### ISSUE TITLE
Evaluate the possibility of using an API to add comments to a Google Doc or Word doc

### ISSUE THREAD

**Issue by kcarnold** [AIToolsLab/questions#1]
Success looks like: a script is run, and every word that starts with `q` gets a comment that contains how many letters that word contains.

Resources:
- https://developers.google.com/drive/api/guides/manage-comments#anchor

**Comment by RayHCai** [comment]
Looks like you can add anchored comments to google docs: [https://stackoverflow.com/questions/23498275/creating-anchored-comments-programmatically-in-google-docs](url), only file-level comments.

**Comment by kcarnold** [comment]
Due to fundamental limitations in Google Docs not being able to add anchored comments programmatically, we're running with a Word addin.
