### ISSUE TITLE
Add-in to figure out

### ISSUE THREAD

**Issue by kcarnold** [AIToolsLab/questions#11]
- Is there a way to have comments added as "by" a bot?
- Can we get alerted when the user moves their cursor around? Might that alert "come with" what text they might be focused on, so we can send that to the server?
- How do we collaborate using, say, git?

Ken's last snapshot
https://gist.github.com/kcarnold/3ddd2ee34382ed6c35713ab794efb4b5

**Comment by SophiaSun18** [comment]
- How to send the body of the document to the server side to be processed by the model?
- Figure out a solution for multiple same words in one paragraph: which is the one we need to add comment on?

**Comment by kcarnold** [comment]
Where is the code for this?

**Comment by SophiaSun18** [comment]
https://github.com/SophiaSun18/OfficeAddIn_addCommentToDoc

**Comment by kcarnold** [comment]
I think we generally figured all this out!
