### ISSUE TITLE
Explore breakthroughs and recent progress in question generation

### ISSUE THREAD

**Issue by nghtctrl** [AIToolsLab/questions#6]
**Goal**: to explore and learn about what work has been done in the research area of question generation, and for potentially discovering sources of inspiration and direction.

What our lab has done so far:

- [HAI-GEN 2021 paper](https://kenarnold.org/pubs/iui21-help-writers/arnold21GenerativeWriting.pdf)
- [Senior Project 2021 paper](https://drive.google.com/file/d/1tUyPhk9ePAeYYJh_T6nqyXttOsvmFExE/view)
- [Summer Research 2021 paper](https://docs.google.com/document/d/146MZLUcd2ZL7G0Y3WteGILzsJZTpo1AUBJp7mxOALo4/edit)

List of potential resources:

- [Papers With Code](https://paperswithcode.com/task/question-generation)

**Comment by kcarnold** [comment]
@nghtctrl what does finishing this task look like? Can we close?
